CREATE DATABASE IF NOT EXISTS castuo_system CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE castuo_system;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_uid VARCHAR(64) NOT NULL UNIQUE,
  email VARCHAR(190) NOT NULL UNIQUE,
  role VARCHAR(64) NOT NULL DEFAULT 'farmer',
  full_name VARCHAR(190) NOT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS farms (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  farm_uid VARCHAR(64) NOT NULL UNIQUE,
  owner_user_uid VARCHAR(64) NOT NULL,
  farm_name VARCHAR(190) NOT NULL,
  location_geojson JSON NULL,
  surface_hectares DECIMAL(10,2) NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_farms_owner (owner_user_uid),
  CONSTRAINT fk_farms_owner_user_uid FOREIGN KEY (owner_user_uid) REFERENCES users(user_uid)
    ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS transactions (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  tx_uid VARCHAR(128) NOT NULL UNIQUE,
  farm_uid VARCHAR(64) NOT NULL,
  tx_type VARCHAR(64) NOT NULL,
  amount DECIMAL(16,4) NULL,
  currency VARCHAR(8) NULL,
  metadata JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_transactions_farm (farm_uid),
  CONSTRAINT fk_transactions_farm_uid FOREIGN KEY (farm_uid) REFERENCES farms(farm_uid)
    ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS logs (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  level VARCHAR(16) NOT NULL,
  source VARCHAR(64) NOT NULL,
  message TEXT NOT NULL,
  payload JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_logs_level_created (level, created_at)
) ENGINE=InnoDB;
