#!/usr/bin/env bash
# generate_credentials.sh
# Genera credenciales seguras y crea (o sobrescribe) el archivo `.env`.
#
# Requisitos:
# - `openssl` instalado (Ubuntu/Debian: apt install openssl)
#
set -euo pipefail

if ! command -v openssl >/dev/null 2>&1; then
  echo "❌ openssl no está instalado. Instálalo: apt install -y openssl"
  exit 1
fi

timestamp_utc="$(date -u '+%Y-%m-%dT%H:%M:%SZ')"

# Entropía robusta para secretos (evita caracteres problemáticos usando base64).
N8N_BASIC_AUTH_PASSWORD="$(openssl rand -base64 24 | tr -d '\n')"
KEYCLOAK_ADMIN_PASSWORD="$(openssl rand -base64 24 | tr -d '\n')"
POSTGRES_KEYCLOAK_PASSWORD="$(openssl rand -base64 24 | tr -d '\n')"
CASTUO_MQTT_PASS="$(openssl rand -base64 24 | tr -d '\n')"
KEYCLOAK_CLIENT_SECRET="$(openssl rand -base64 24 | tr -d '\n')"

# Defaults operativos para el stack.
CASTUO_MQTT_USER="${CASTUO_MQTT_USER:-n8n-user}"
N8N_BASIC_AUTH_USER="${N8N_BASIC_AUTH_USER:-admin}"
KEYCLOAK_CLIENT_ID="${KEYCLOAK_CLIENT_ID:-n8n-admin}"

GAIA_CHAIN_AUDIT_CONTRACT="${GAIA_CHAIN_AUDIT_CONTRACT:-0x123...abc}"
GAIA_CHAIN_AUDIT_ABI="${GAIA_CHAIN_AUDIT_ABI:-{\"inputs\": [], \"name\": \"registerEvent\"}}"
GAIA_CHAIN_PRIVATE_KEY="${GAIA_CHAIN_PRIVATE_KEY:-0x0}"
ZERO_LEAK_OUT_URL="${ZERO_LEAK_OUT_URL:-https://destino-seguro.example/api}"

# Nota: N8N_ADMIN_JWT se genera a través de Keycloak (client_credentials) una vez
# el stack esté levantado y el client/roles existan. Aquí lo dejamos en blanco.
N8N_ADMIN_JWT="${N8N_ADMIN_JWT:-}"

# Escribe .env
cat > .env <<EOL
# Auto-generated by generate_credentials.sh on ${timestamp_utc}

# ===== AUTH =====
N8N_USER=${N8N_BASIC_AUTH_USER}
N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}

KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
POSTGRES_KEYCLOAK_PASSWORD=${POSTGRES_KEYCLOAK_PASSWORD}

# ===== MQTT (autenticado) =====
CASTUO_MQTT_USER=${CASTUO_MQTT_USER}
CASTUO_MQTT_PASS=${CASTUO_MQTT_PASS}

# ===== GaiaChain audit =====
GAIA_CHAIN_AUDIT_CONTRACT=${GAIA_CHAIN_AUDIT_CONTRACT}
GAIA_CHAIN_AUDIT_ABI='${GAIA_CHAIN_AUDIT_ABI}'
GAIA_CHAIN_PRIVATE_KEY=${GAIA_CHAIN_PRIVATE_KEY}

# ===== Destino externo (ciphertext + signature) =====
ZERO_LEAK_OUT_URL=${ZERO_LEAK_OUT_URL}

# ===== JWT Admin (se rellena tras levantar Keycloak) =====
N8N_ADMIN_JWT=${N8N_ADMIN_JWT}
EOL

echo "✅ Credenciales generadas en `.env` (${timestamp_utc}):"
echo "   - N8N_BASIC_AUTH_PASSWORD: (generado)"
echo "   - KEYCLOAK_ADMIN_PASSWORD: (generado)"
echo "   - POSTGRES_KEYCLOAK_PASSWORD: (generado)"
echo "   - CASTUO_MQTT_USER: ${CASTUO_MQTT_USER}"
echo "   - CASTUO_MQTT_PASS: (generado)"
echo
echo "📌 Nota:"
echo "   - La variable `N8N_ADMIN_JWT` se completa después de levantar Keycloak"
echo "     (cuando el client `n8n-admin` y su rol `admin` existan)."
echo
echo "📌 Siguiente paso recomendado:"
echo "   docker-compose -f docker-compose.hetzner.zero-leak.yml up -d"

