apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: agroedu-monitor
  namespace: education
spec:
  selector:
    matchLabels:
      app: agroedu
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
