apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: castuo-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - api.castuo-system.cloud
    secretName: castuo-tls
  rules:
  - host: api.castuo-system.cloud
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: castuo-api-service
            port:
              number: 80
