{
    "name": "CASTUO System",
    "version": "1.1.0",
    "category": "Operations",
    "summary": "CRM/ERP/Legal + Drones, IoT, Riego, Energía, Chatbot para granjas CASTUO",
    "depends": ["base", "mail", "crm", "account"],
    "data": [
        "data/chatbot_sequence.xml",
        "security/ir.model.access.csv",
        "views/granja_views.xml",
        "views/licencia_views.xml",
        "views/epcis_event_views.xml",
        "views/factura_views.xml",
        "views/drone_views.xml",
        "views/camera_views.xml",
        "views/sensor_views.xml",
        "views/teledeteccion_views.xml",
        "views/riego_views.xml",
        "views/energia_views.xml",
        "views/chatbot_views.xml",
        "views/energia_market_views.xml",
        "views/robot_views.xml",
        "views/asset_token_views.xml",
        "views/material_views.xml",
    ],
    "installable": True,
    "application": True,
}

