apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "castuo-system.fullname" . }}-config
  labels:
    {{- include "castuo-system.labels" . | nindent 4 }}
data:
  RABBITMQ_HOST: "{{ .Release.Name }}-rabbitmq"
  RABBITMQ_PORT: "5672"
  PROMETHEUS_URL: "http://{{ .Release.Name }}-prometheus-server:9090"
  VAULT_ADDR: "http://{{ .Release.Name }}-vault:8200"
  OPA_URL: "http://{{ .Release.Name }}-opa:8181"
  LOG_LEVEL: "{{ .Values.logLevel | default "INFO" }}"
  CACHE_TTL: "{{ .Values.agents.cacheTTL | default "3600" }}"
