apiVersion: apps/v1
kind: Deployment
metadata:
  name: crop-nft-marketplace
  namespace: castuo-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crop-nft-marketplace
  template:
    metadata:
      labels:
        app: crop-nft-marketplace
    spec:
      containers:
        - name: marketplace
          image: ghcr.io/castuo-system/crop-nft-marketplace:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: crop-nft-marketplace
  namespace: castuo-system
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: crop-nft-marketplace
