apiVersion: v1
kind: Service
metadata:
  name: castuo-backend
  namespace: castuo-system
spec:
  selector:
    app: castuo-backend
  ports:
  - port: 8000
    targetPort: 8000
    name: http
  type: ClusterIP
