apiVersion: apps/v1
kind: Deployment
metadata:
  name: castuo-backend
  namespace: castuo-system
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: backend
        image: ghcr.io/castuo-system/backend:v1.4.0
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
