apiVersion: v1
kind: Secret
metadata:
  name: gaiachain-secrets
  namespace: castuo-system
type: Opaque
stringData:
  GAIACHAIN_ENDPOINT: https://gaiachain.eu
  GAIACHAIN_API_KEY: CHANGE_ME
  OPENEVIDENCE_API_KEY: CHANGE_ME
