# ACL granulares — usuarios en passwd (init-passwd)

user admin
topic readwrite #

user sensor_orp
topic write castuo/water/sensor/orp

user sensor_tds
topic write castuo/water/sensor/tds

user sensor_ph
topic write castuo/water/sensor/ph

user actuator_ozone
topic readwrite castuo/water/actuator/ozone

user actuator_osmosis
topic readwrite castuo/water/actuator/osmosis

user n8n_system
topic read castuo/water/sensor/+
topic write castuo/water/actuator/+
topic read $SYS/#
