[rpis_eu]
rpi-eu-001 ansible_host=192.168.1.101 ansible_user=pi
rpi-eu-002 ansible_host=192.168.1.102 ansible_user=pi

[rpis_latam]
rpi-latam-001 ansible_host=192.168.2.101 ansible_user=pi

[rpis_asia]
rpi-asia-001 ansible_host=192.168.3.101 ansible_user=pi

[rpis:children]
rpis_eu
rpis_latam
rpis_asia
