apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patchesStrategicMerge:
  - deployment-patch.yaml
configMapGenerator:
  - name: castuo-config
    literals:
      - PORT_HIDRO=8001
      - DB_URL=postgresql://user:pass@postgres-latam:5432/castuo
      - MQTT_USER=latam_user
      - REGION=latam
